<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.0.0.379
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Home Form إرسال',
	'heading' => 'إرسال نموذج جديد',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'تم التحديد',
		'checkbox_unchecked' => 'تم إلغاء التحديد',
		'submitted_from' => 'تم إرسال النموذج من موقع الويب: %s',
		'submitted_by' => 'عنوان IP الخاص بالزائر: %s',
		'too_many_submissions' => 'صدر عن عنوان IP هذا مؤخرًا عدد كبير جدًا من عمليات الإرسال',
		'failed_to_send_email' => 'فشل إرسال البريد الإلكتروني',
		'invalid_reCAPTCHA_private_key' => 'مفتاح reCAPTCHA الخاص غير صالح.',
		'invalid_reCAPTCHA2_private_key' => 'Invalid reCAPTCHA 2.0 private key.',
		'invalid_reCAPTCHA2_server_response' => 'Invalid reCAPTCHA 2.0 server response.',
		'invalid_field_type' => 'نوع حقل غير معروف \'%s\'.',
		'invalid_form_config' => 'للحقل \'%s\' تكوين غير صالح.',
		'unknown_method' => 'أسلوب طلب الخادم غير معروف'
	),
	'email' => array(
		'from' => 'messahelm@gmail.com',
		'to' => 'messahelm@gmail.com'
	),
	'fields' => array(
		'custom_U2621' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'الاسم',
			'required' => true,
			'errors' => array(
				'required' => 'الحقل \'الاسم\' مطلوب.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'البريد الإلكتروني',
			'required' => true,
			'errors' => array(
				'required' => 'الحقل \'البريد الإلكتروني\' مطلوب.',
				'format' => 'للحقل \'البريد الإلكتروني\' عنوان بريد إلكتروني غير صالح.'
			)
		),
		'custom_U2615' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'الرسالة',
			'required' => false,
			'errors' => array(
			)
		)
	)
);

process_form($form);
?>
